Simplify installer
npezza93/solid_cable pull request #5
Opened 2024-09-09 19:40 UTC by fractaledmind

This matches the structure that Solid Queue now uses (after https://github.com/rails/solid_queue/pull/321) and Solid Cache now uses (after https://github.com/rails/solid_cache/pull/202)

2024-09-09 20:21 UTC, npezza93 requested changes
Few text tweaks then this is good to go! Thanks!

2024-09-09 20:21 UTC, npezza93 commented on README.md
> +You will then have to add the configuration for the errors database in `config/database.yml`. If you're using sqlite, it'll look something like this:
```suggestion
You will then have to add the configuration for the database in `config/database.yml`. If you're using SQLite, it'll look something like this:
```

2024-09-09 20:21 UTC, npezza93 commented on README.md
> +> Calling `bin/rails generate solid_cable:install` will automatically setup `config/cable.yml`, so no additional configuration is needed there (although you must make sure that you use the `cable` na
```suggestion
> Calling `bin/rails generate solid_cable:install` will automatically setup `config/cable.yml`, so no additional configuration is needed there (although you must make sure that you use the `cable` name in `database.yml` for this to match!). But if you want to use Solid Cable in a different environment (like staging or even development), you'll have to manually add that `connects_to` block to the respective environment in the `config/cable.yml` file. And, as always, make sure that the name you're using for the database in `config/cable.yml` matches the name you define in `config/database.yml`.
```

2024-09-10 08:47 UTC, fractaledmind commented
@npezza93: Thanks. Updated

2024-09-10 14:22 UTC, npezza93 approved these changes

2024-09-10 14:23 UTC, merged